name = "Quilt Modpack"
author = "Arthurmeade12"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "199a086c0a9ab3a11b493fb7bf78fe57e0a844ca5e0c7d2b8079983eb2e8129b"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
